config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'static_pages#index'

namespace :instructor do 
		resources :program_names do 
			resources :weeks
		end
	end
	
	namespace :instructor do 
		resources :weeks do
			resources :titles
		end
	end
	namespace :instructor do
		resources :titles do
			resources :programs

		end	
	end
	namespace :instructor do 
		resources :weeks do
			resources :titles do 
				resources :programs 
			end
		end
	end
	
	resources :program_names, only: [:index, :show] do 
		resources :weeks, only: [:index, :show]
	end
	resources :weeks, only: [:index, :show] do 
		resources :titles, only: [:index, :show, ]
	end
	resources :titles, only: [:index, :show, :edit, :update] do
		resources :programs, only: [:index, :show]
	end
match '/weeks/complete/:id' => 'weeks#complete', as: 'complete_week', via: :put
match '/weeks/complete/:id' => 'weeks#incomplete', as: 'incomplete_week', via: :delete
match '/titles/complete/:id' => 'titles#complete', as: 'complete_title', via: :put
match '/titles/complete/:id' => 'titles#incomplete', as: 'incomplete_title', via: :delete


	resources :max_weights, only: [:index, :new, :create, :show]
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/max_weight.rb
class MaxWeight < ApplicationRecord
belongs_to :user
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :title
	default_scope { order(created_at: :asc) }
	
	
end

app/models/program_name.rb
class ProgramName < ApplicationRecord
belongs_to :user
has_many :weeks, :dependent => :destroy
end

app/models/title.rb
class Title < ApplicationRecord
	belongs_to :week
	has_many :programs, :dependent => :destroy
	default_scope { order(created_at: :asc) }
scope :completed, -> { where(title_completed: true) }
scope :incomplete, -> { where(title_completed: false) }

	
	

end

app/models/user.rb
class User < ApplicationRecord
 has_many :program_names, :dependent => :destroy
 
 has_many :max_weights
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/week.rb
class Week < ApplicationRecord
belongs_to :program_name
has_many :titles, :dependent => :destroy
default_scope { order(created_at: :asc) }

scope :completed, -> { where(week_completed: true) }
scope :incomplete, -> { where(week_completed: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/max_weights_controller.rb
class MaxWeightsController < ApplicationController
	before_action :authenticate_user!
	def new
		@max_weight = MaxWeight.new

	end

	def create
		@max_weight = current_user.max_weights.create(max_weight_params)
		redirect_to root_path
		

	end

	

	def show
		@max_weight = MaxWeight.find(params[:id])
	end

	

	private

	def max_weight_params
		params.require(:max_weight).permit(:max_bench, :max_squat, :max_deadlift)
	end

end

app/controllers/program_names_controller.rb
class ProgramNamesController < ApplicationController
def index
	@program_names = ProgramName.all
	

end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
def index
		@titles = Title.all
		@programs = Program.all
		

	end

	def show
		@title = Title.find(params[:title_id])
		@user = User.all
		@program = Program.find(params[:id])
		@max_weight = MaxWeight.all
		@max_bench = MaxWeight.max_bench
		@max_squat = MaxWeight.max_squat
		@max_deadlift = MaxWeight.max_deadlift
		
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!
def index
	@max = MaxWeight.count
	
end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_week, only: [:show]
	def index
		
		@titles = Title.all
		@weeks = Week.all	
		@week = Week.find(params[:week_id])	
	end

	def show	
		@title = Title.find(params[:id])
		@user = User.all
		
		@max_weight = current_user.max_weights.last

		@max_bench = @max_weight.max_bench
		@max_squat = @max_weight.max_squat
		@max_deadlift = @max_weight.max_deadlift
		@number = 600
				
	end

def complete
	
@title =  Title.find(params[:id])
@title.title_completed = true
@title.save
redirect_back(fallback_location: root_path)
end

def incomplete
@title = Title.find(params[:id])
@title.title_completed = false
@title.save
redirect_back(fallback_location: root_path)
	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end

	
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
def index
	@program_name = ProgramName.find(params[:program_name_id])
	@program_names = ProgramName.all
	@weeks = Week.all

end

def complete
@week = Week.find(params[:id])
@week.week_completed = true
@week.save
redirect_back(fallback_location: root_path)

	end

	def incomplete
		@week = Week.find(params[:id])
		@week.week_completed = false
		@week.save
		redirect_back(fallback_location: root_path)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructor/weeks_helper.rb
module Instructor::WeeksHelper
end

app/helpers/max_weights_helper.rb
module MaxWeightsHelper
end

app/helpers/program_names_helper.rb
module ProgramNamesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	

end

app/helpers/titles_helper.rb
module TitlesHelper
	
	
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/static_pages/index.html.erb
<div class="hero">
    <div class="container h-100 text-center">
        <div class="row align-items-center h-100">
            <div class="col-12 mx-auto">
                <br />
                <div class="row">
                    <div class="col-12 black">
                        <h1 id="index"> If You're Gonna Be Fat...
                            <br />
                            You Gotta Be Strong.</h1>
                        <br />
                    </div>
                </div>
                <br />
                <%= link_to 'View Your Workout', program_names_path, class: 'btn btn-success' %>
                <br />
                <br />
                <%= link_to 'Enter Max Weight', new_max_weight_path, class: 'btn btn-success' %>
                <br />
                <br />
                <br />
                <br />
                <div class="row no-gutters">
                    <div class="col-2 offset-3 hide-create-workout">
                        <%= link_to 'Create a Program', new_instructor_program_name_path, class: 'yellow btn btn-whatever' %>
                    </div>
                    <div class="col-2 offset-2 hide-create-workout">
                        <%= link_to 'View Programs', instructor_program_names_path, class: 'yellow btn btn-whatever' %>
                    </div>
                </div>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </div>
    </div>
</div>