config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'static_pages#index'

namespace :instructor do 
		resources :program_names do 
			resources :weeks
		end
	end
	
	namespace :instructor do 
		resources :weeks do
			resources :titles
		end
	end
	namespace :instructor do
		resources :titles do
			resources :programs

		end	
	end
	namespace :instructor do 
		resources :weeks do
			resources :titles do 
				resources :programs 
			end
		end
	end
	
	resources :program_names, only: [:index, :show] do 
		resources :weeks, only: [:index, :show]
	end
	resources :weeks, only: [:index, :show] do 
		resources :titles, only: [:index, :show, ]
	end
	resources :titles, only: [:index, :show, :edit, :update] do
		resources :programs, only: [:index, :show]
	end
match '/weeks/complete/:id' => 'weeks#complete', as: 'complete_week', via: :put
match '/weeks/complete/:id' => 'weeks#incomplete', as: 'incomplete_week', via: :delete
match '/titles/complete/:id' => 'titles#complete', as: 'complete_title', via: :put
match '/titles/complete/:id' => 'titles#incomplete', as: 'incomplete_title', via: :delete


	resources :max_weights, only: [:index, :new, :create, :show]
	
end

app/models/title.rb
class Title < ApplicationRecord
	belongs_to :week
	has_many :programs, :dependent => :destroy
	default_scope { order(created_at: :asc) }
scope :completed, -> { where(title_completed: true) }
scope :incomplete, -> { where(title_completed: false) }

	
	

end

app/controllers/instructor/program_names_controller.rb
class Instructor::ProgramNamesController < ApplicationController
before_action :authenticate_user! 
before_action :set_program_name, only: [:edit, :update, :destroy]

def index
	@program_names = ProgramName.all

end
def new
	@program_name = ProgramName.new

end

def create
	@program_name = current_user.program_names.create(program_name_params)
redirect_to instructor_program_names_path(@program_name)
	end

	def edit
		

	end
	def update
		
		@program_name.update_attributes(program_name_params)
		redirect_to instructor_program_names_path

	end

	def destroy
		
		@program_name.destroy
		redirect_to instructor_program_names_path

	end

	private

	def set_program_name
		@program_name ||= ProgramName.find(params[:id])

	end

def program_name_params
	params.require(:program_name).permit(:program_name)
end

end

app/controllers/instructor/programs_controller.rb
class Instructor::ProgramsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_week, only: [:create, :update, :destroy]
	before_action :set_title, only: [:index, :create, :update, :destroy]
	
	def new
		@program = Program.new
	end

	def index
		@titles = Title.all 
		@programs = Program.all
	end

	def create
		
		@program = @title.programs.create(program_params)
		redirect_to instructor_week_title_path(@week,@title)
	end
	def edit
		@program = Program.find(params[:id])
	end

	def update
		@program = Program.find(params[:id])
		@program.update_attributes(program_params)
		redirect_to instructor_week_title_path(@week,@title)

	end
	def destroy

		@program = Program.find(params[:id])
		@program.destroy
		redirect_to instructor_week_title_path(@week, @title)

	end

	private
	def set_week
@week = Week.find(params[:week_id])
	end
def set_title
@title = Title.find(params[:title_id])
end 


	def program_params
		params.require(:program).permit(:exercise, :sets, :reps, :intensity, :prescribed_load, :actual_load, :tempo, :rest, :notes, :title_id)
	end
end

app/controllers/instructor/titles_controller.rb
class Instructor::TitlesController < ApplicationController
	before_action :authenticate_user!
	
	before_action :set_week, only: [:new, :show, :edit, :index, :create, :update, :destroy]
	before_action :set_title, only: [:show, :edit, :update, :destroy]

	

	def new
		@title = Title.new
	end

	def index
		@weeks = Week.all
		@titles = Title.all
		
	end

	def create
		@title = @week.titles.create(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week,@title)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show

		@titles = Title.all
		@programs = Program.all
	end

	def edit
		set_title
	end

	def update
		@title.update_attributes(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week, @title)
		else
			render :edit, status: :unprocessable_entity
		end

	end

	def destroy	
		@title.destroy
		redirect_to instructor_week_titles_path(@week)

	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end
	def set_title
		@title ||= Title.find(params[:id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end
end

app/controllers/instructor/weeks_controller.rb
class Instructor::WeeksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_program_name, only: [:new, :index, :create, :edit]
	before_action :set_week, only: [:show, :edit, :update, :destroy]
	def new	
		@week = Week.new
	end

	def create	
		@program_name.weeks.create(week_params)
		redirect_to instructor_program_name_weeks_path(@program_name)
	end

	def index
		@program_names = ProgramName.all
		@weeks = Week.all
	end

	def show
		set_week
	end

	def edit
		@program_names = ProgramName.all
		@weeks = Week.all
	end

	def update
		@week.update_attributes(week_params)
		if @week.valid?
			redirect_to instructor_program_name_weeks_path
		else
			render :edit, status: :unprocessable_entity
		end

	end
	def destroy
		@week.destroy
		redirect_to instructor_program_name_weeks_path
	end

	private

	def set_program_name
		@program_name ||= ProgramName.find(params[:program_name_id])
	end
	def set_week
		@week  ||= Week.find(params[:id])

	end
	def week_params
		params.require(:week).permit(:week_name)

	end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_week, only: [:show]
	def index
		
		@titles = Title.all
		@weeks = Week.all	
		@week = Week.find(params[:week_id])	
	end

	def show	
		@title = Title.find(params[:id])
		@user = User.all
		
		@max_weight = current_user.max_weights.last

		@max_bench = @max_weight.max_bench
		@max_squat = @max_weight.max_squat
		@max_deadlift = @max_weight.max_deadlift
		@number = 600
				
	end

def complete
	
@title =  Title.find(params[:id])
@title.title_completed = true
@title.save
redirect_back(fallback_location: root_path)
end

def incomplete
@title = Title.find(params[:id])
@title.title_completed = false
@title.save
redirect_back(fallback_location: root_path)
	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end

	
end

app/helpers/instructor/program_names_helper.rb
module Instructor::ProgramNamesHelper
end

app/helpers/instructor/programs_helper.rb
module Instructor::ProgramsHelper
end

app/helpers/instructor/titles_helper.rb
module Instructor::TitlesHelper
end

app/helpers/instructor/weeks_helper.rb
module Instructor::WeeksHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
	
	
end

app/views/instructor/titles/edit.html.erb
<br />
<div class="booyah-box col-10 offset-1  text-center">
    <h1> Edit Title</h1>
    <%= simple_form_for @title, url: instructor_week_title_path do |f| %>
    <div class="container ">
        <div class="row">
            <div class="col-8 offset-2">
                <%= f.input :title, placeholder: "ex Week1 Day1 " %>
            </div>
        </div>
        <%= f.submit 'Update', class: 'btn btn-success' %>
        <% end %>
    </div>
    <br />
</div>

app/views/instructor/titles/index.html.erb
<br />
<div class="booyah-box col-10 offset-1">
    <h2 class="text-center">Workout Days</h2>
    <br />
    <h1>
        <%= @week.week_name %>
    </h1>
    <% @week.titles.each do |title| %>
    <h3 class="links text-center">
        <%= link_to title.title, instructor_week_title_path(@week,title) %>
        &nbsp;&nbsp;
        <%=link_to  edit_instructor_week_title_path(@week,title),  class: 'edit-symbol' do %>
        <i class="far fa-edit" style="color:white"></i>
        <% end %>&nbsp;&nbsp;
        <%= link_to instructor_week_title_path(@week, title), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'delete-symbol' do %>
        <i class="far fa-trash-alt" style='color:white'></i>
        <% end %>
    </h3>
    <br />
    <% end %>
    <div class="text-center">
        <%= link_to 'Create Workout Day', new_instructor_week_title_path(@week), class: 'btn btn-success btn-large' %>
    </div>
    <br />
    <div class="text-center">
        <%= link_to 'View Programs', instructor_program_names_path, class: 'btn btn-success btn-large' %>
    </div>
    <br />
</div>
<br />
<br />
<div class="text-center">
    <%= link_to 'Homepage', root_path, class: 'btn btn-success btn-large' %>
    <br />
</div>
<br />
<br />

app/views/instructor/titles/new.html.erb
<br />
<div class="booyah-box col-10 offset-1  text-center">
    <h1> Add a new Workout Day</h1>
    <%= simple_form_for @title, url: instructor_week_titles_path do |f| %>
    <div class="container ">
        <div class="row">
            <div class="col-8 offset-2">
                <%= f.input :title, placeholder: "ex Week1 Day1 " %>
            </div>
        </div>
        <br />
        <%= f.submit "Create", class: 'btn btn-success' %>
        <% end %>
    </div>
    <br />
</div>

app/views/instructor/titles/show.html.erb
<div class="booyah-box col-10 offset-1">
    <h1 class="text-center">
        <%=@title.title%>
    </h1>
    <br class="clr" />
    <div class="container">
        <div class="row">
            <div class="col-4 text-center">
                <%= link_to 'Add Movement ', new_instructor_week_title_program_path(@week,@title), class: 'btn btn-success btn-small' %>
            </div>
            <div class="col-4 offset-3 text-center">
                <%= link_to 'Edit Day', edit_instructor_week_title_path(@week,@title), class: 'btn btn-success btn-small' %>
            </div>
        </div>
        <br />
        <div class="row">
            <br class="clr" />
            <div class="col-4 text-center">
                <%= link_to 'Delete Day', instructor_week_title_path(@week,@title), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger btn-small' %>
            </div>
            <br />
            <div class="col-4 offset-3 text-center">
                <%= link_to ' New Day', new_instructor_week_title_path, class: 'btn btn-success btn-small' %>
            </div>
        </div>
    </div>
    <br />
    <div class="text-center">
        <%= link_to 'All Days', instructor_week_titles_path(@week), class: 'btn btn-success' %>
    </div>
    <br />
</div>
<br />
<div id="hide">
    <div class="booyah-box  col-12">
        <div class=" container padding">
            <table class="table table-striped">
                <thead>
                    <div class="row">
                        <div class="col-1">
                            <tr>
                                <th>
                                    <p> Movement</p>
                                </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p class="text-center">Sets</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p class="text-center">Reps</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p class="text-center"> Intensity</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p class="text-center">Tempo</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p class="text-center">Rest</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p> Edit</p>
                            </th>
                        </div>
                        <div class="col-1">
                            <th>
                                <p> Delete</p>
                            </th>
                        </div>
                    </div>
                    </tr>
                </thead>
                <tbody>
                    <% @title.programs.each do |program| %>
                    <div class="row">
                        <div class="col-1">
                            <tr>
                                <td>
                                    <p>
                                        <%= program.exercise %>
                                    </p>
                                </td>
                        </div>
                        <div class="col-1 text-center">
                            <td>
                                <p class="text-center">
                                    <%= program.sets %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%= program.reps %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%= program.intensity %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%= program.tempo %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%= program.rest %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%=link_to edit_instructor_week_title_program_path(@week,@title, program),  class: "edit-symbol" do %>
                                    <i class="far fa-edit" style="color:white"></i>
                                    <% end %>
                                </p>
                            </td>
                        </div>
                        <div class="col-1">
                            <td>
                                <p class="text-center">
                                    <%= link_to instructor_week_title_program_path(@week,@title,program), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'delete-symbol' do %>
                                    <i class="far fa-trash-alt" style='color:white'></i>
                                    <% end %>
                                </p>
                            </td>
                        </div>
                    </div>
        </div>
        </tr>
        <br />
        <br />
        <% end %>
        </tbody>
        </table>
    </div>
</div>
</div>
<br />
<div class="text-center">
    <%= link_to "Homepage", root_path, class: 'btn btn-success' %>
</div>
&nbsp;
&nbsp;