config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'static_pages#index'

namespace :instructor do 
		resources :program_names do 
			resources :weeks
		end
	end
	
	namespace :instructor do 
		resources :weeks do
			resources :titles
		end
	end
	namespace :instructor do
		resources :titles do
			resources :programs

		end	
	end
	namespace :instructor do 
		resources :weeks do
			resources :titles do 
				resources :programs 
			end
		end
	end
	
	resources :program_names, only: [:index, :show] do 
		resources :weeks, only: [:index, :show]
	end
	resources :weeks, only: [:index, :show] do 
		resources :titles, only: [:index, :show, ]
	end
	resources :titles, only: [:index, :show, :edit, :update] do
		resources :programs, only: [:index, :show]
	end
match '/weeks/complete/:id' => 'weeks#complete', as: 'complete_week', via: :put
match '/weeks/complete/:id' => 'weeks#incomplete', as: 'incomplete_week', via: :delete
match '/titles/complete/:id' => 'titles#complete', as: 'complete_title', via: :put
match '/titles/complete/:id' => 'titles#incomplete', as: 'incomplete_title', via: :delete


	resources :max_weights, only: [:index, :new, :create, :show]
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/max_weight.rb
class MaxWeight < ApplicationRecord
belongs_to :user
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :title
	default_scope { order(created_at: :asc) }
	
	
end

app/models/program_name.rb
class ProgramName < ApplicationRecord
belongs_to :user
has_many :weeks, :dependent => :destroy
end

app/models/title.rb
class Title < ApplicationRecord
	belongs_to :week
	has_many :programs, :dependent => :destroy
	default_scope { order(created_at: :asc) }
scope :completed, -> { where(title_completed: true) }
scope :incomplete, -> { where(title_completed: false) }

	
	

end

app/models/user.rb
class User < ApplicationRecord
 has_many :program_names, :dependent => :destroy
 
 has_many :max_weights
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/week.rb
class Week < ApplicationRecord
belongs_to :program_name
has_many :titles, :dependent => :destroy
default_scope { order(created_at: :asc) }

scope :completed, -> { where(week_completed: true) }
scope :incomplete, -> { where(week_completed: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/instructor/titles_controller.rb
class Instructor::TitlesController < ApplicationController
	before_action :authenticate_user!
	
	before_action :set_week, only: [:new, :show, :edit, :index, :create, :update, :destroy]
	before_action :set_title, only: [:show, :edit, :update, :destroy]

	

	def new
		@title = Title.new
	end

	def index
		@weeks = Week.all
		@titles = Title.all
		
	end

	def create
		@title = @week.titles.create(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week,@title)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show

		@titles = Title.all
		@programs = Program.all
	end

	def edit
		set_title
	end

	def update
		@title.update_attributes(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week, @title)
		else
			render :edit, status: :unprocessable_entity
		end

	end

	def destroy	
		@title.destroy
		redirect_to instructor_week_titles_path(@week)

	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end
	def set_title
		@title ||= Title.find(params[:id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end
end

app/controllers/max_weights_controller.rb
class MaxWeightsController < ApplicationController
	before_action :authenticate_user!
	def new
		@max_weight = MaxWeight.new

	end

	def create
		@max_weight = current_user.max_weights.create(max_weight_params)
		redirect_to root_path
		

	end

	

	def show
		@max_weight = MaxWeight.find(params[:id])
	end

	

	private

	def max_weight_params
		params.require(:max_weight).permit(:max_bench, :max_squat, :max_deadlift)
	end

end

app/controllers/program_names_controller.rb
class ProgramNamesController < ApplicationController
def index
	@program_names = ProgramName.all
	

end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
def index
		@titles = Title.all
		@programs = Program.all
		

	end

	def show
		@title = Title.find(params[:title_id])
		@user = User.all
		@program = Program.find(params[:id])
		@max_weight = MaxWeight.all
		@max_bench = MaxWeight.max_bench
		@max_squat = MaxWeight.max_squat
		@max_deadlift = MaxWeight.max_deadlift
		
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!
def index
	@max = MaxWeight.count
	
end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_week, only: [:show]
	def index
		
		@titles = Title.all
		@weeks = Week.all	
		@week = Week.find(params[:week_id])	
	end

	def show	
		@title = Title.find(params[:id])
		@user = User.all
		
		@max_weight = current_user.max_weights.last

		@max_bench = @max_weight.max_bench
		@max_squat = @max_weight.max_squat
		@max_deadlift = @max_weight.max_deadlift
		@number = 600
				
	end

def complete
	
@title =  Title.find(params[:id])
@title.title_completed = true
@title.save
redirect_back(fallback_location: root_path)
end

def incomplete
@title = Title.find(params[:id])
@title.title_completed = false
@title.save
redirect_back(fallback_location: root_path)
	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end

	
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
def index
	@program_name = ProgramName.find(params[:program_name_id])
	@program_names = ProgramName.all
	@weeks = Week.all

end

def complete
@week = Week.find(params[:id])
@week.week_completed = true
@week.save
redirect_back(fallback_location: root_path)

	end

	def incomplete
		@week = Week.find(params[:id])
		@week.week_completed = false
		@week.save
		redirect_back(fallback_location: root_path)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructor/programs_helper.rb
module Instructor::ProgramsHelper
end

app/helpers/instructor/titles_helper.rb
module Instructor::TitlesHelper
end

app/helpers/instructor/weeks_helper.rb
module Instructor::WeeksHelper
end

app/helpers/max_weights_helper.rb
module MaxWeightsHelper
end

app/helpers/program_names_helper.rb
module ProgramNamesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	

end

app/helpers/titles_helper.rb
module TitlesHelper
	
	
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/titles/index.html.erb
<br />
<br />
<div class="booyah-box col-10 offset-1">
    <h1 class="text-center">You Gotta Be Stronger</h1>
    <hr />
    <h1>
        <%= @week.week_name %>
    </h1>
    <% @week.titles.incomplete.each do |title| %>
    <h2 class="text-center">
        <%= link_to title.title, week_title_path(@week, title) %>
        &nbsp;&nbsp;
        <%= link_to complete_title_path(title), method: :put, class: 'check-symbol' do %>
        <i class="far fa-check-circle" style="color:green"></i>
        <% end %>
    </h2>
    <% end %>
    <br />
    <div class="text-center">
        <%= link_to 'Back to Program Weeks', program_name_weeks_path(@week.program_name.id), class: 'btn btn-success btn-large' %>
    </div>
    <br />
</div>
<br />
<div class=" booyah-box col-10 offset-1">
    <h1 class="grey text-center">Completed Workouts</h1>
    <hr />
    <h1 class="grey">
        <%= @week.week_name %>
    </h1>
    <% @week.titles.completed.each do |title| %>
    <h2 class="text-center test">
        <%= link_to title.title, week_title_path(@week, title) %> &nbsp;&nbsp;
        <%= link_to  incomplete_title_path(title), method: :delete, class: 'check-symbol' do %>
        <i class="far fa-check-circle" style="color:red"></i>
        <% end %>
    </h2>
    <br />
    <% end %>
</div>
<br />
<div class="text-center">
    <%= link_to 'Homepage', root_path, class: 'btn btn-success btn-large' %>
</div>

app/views/titles/show.html.erb
<br />
<div class="booyah-box col-12">
    <br />
    <br />
    <h1>
        <%= @title.title %>
    </h1>
    <div id="show-when-small">
        <h3 class="text-center"> Your screen is too small.<br />
            Flip to landscape mode to view workout</h3>
    </div>
    <div id="hide-when-small">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <p> Movement</p>
                </div>
                <div class="col-1">
                    <p class="text-center">Sets</p>
                </div>
                <div class="col-1">
                    <p class="text-center">Reps</p>
                </div>
                <div class="col-2">
                    <p class="text-center"> Intensity</p>
                </div>
                <div class="col-1">
                    <p class="text-center"> Load</p>
                </div>
                <div class="col-2">
                    <p class="text-center">Tempo</p>
                </div>
                <div class="col-2">
                    <p class="text-center">Rest</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div style='border-bottom:1px solid #ccc;'></div>
                </div>
            </div>
            <script>
            var rest_in_seconds = [];
            var click = 0;
            </script>
            <%= counter = 0 %>
            <% @title.programs.each do |program| %>
            <div class="row">
                <div class="col-2">
                    <p>
                        <%= program.exercise %>
                </div>
                <div class="col-1 text-center">
                    <p class="text-center">
                        <%= program.sets %>
                    </p>
                </div>
                <div class="col-1">
                    <p class="text-center">
                        <%= program.reps %>
                    </p>
                </div>
                <div class="col-2">
                    <p class="text-center">
                        <% if program.intensity.nil? %>
                        <% ""%>
                        <% elsif program.intensity < 20 %>
                        <% "-" %>
                        <% else %>
                        <%= program.intensity%>%
                        <% end %>
                    </p>
                </div>
                <div class="col-1">
                    <p class="text-center">
                        <% if @max_bench && @max_squat && @max_deadlift %>
                        <% if program.intensity.nil? %>
                        <%= "-" %>
                        <% elsif program.intensity.present?  && program.intensity < 20 %>
                        <%= program.intensity%>RPE
                        <% elsif program.exercise.include? "quat"   %>
                        <%= (@max_squat * (program.intensity * 0.01)).to_i %>lbs.
                        <% elsif program.exercise.include? "Bench"  %>
                        <%= (@max_bench * (program.intensity * 0.01)).to_i %>lbs.
                        <% elsif program.exercise.include? "Dead"  %>
                        <%= (@max_deadlift * (program.intensity * 0.01)).to_i %>lbs.
                        <% elsif program.intensity.nil? %>
                        <% "-" %>
                        <% else %>
                        <%= "" %>
                        <% end %>
                        <% else %>
                        <%= "" %>
                        <% end %>
                    </p>
                </div>
                <div class="col-2">
                    <p class="text-center">
                        <%= program.tempo %>
                    </p>
                </div>
                <div class="col-2">
                    <p class="text-center">
                        <%= program.rest %> secs
                    </p>
                </div>
            </div>
            <div class="row ">
                <div class="col-2 offset-5 text-center">
                    <h1 id="demo<%=counter%>">
                        <script>
                        rest_in_seconds[<%=counter%>] = <%=program.rest%>;
                        </script>
                    </h1>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-2 text-center ">
                    <button class="showTimerButton" id="showTimer<%=counter%>" name="timer" value="Show Div" onclick="showTimer(<%=counter%>)">Show Timer</button>
                </div>
            </div>
            <div id="timerButtons<%=counter%>" style="display:none;">
                <div class="row">
                    <div class="col-2 offset-2 text-center">
                        <button class="timerButton" id="button1<%=counter%>" onclick="switchButtons(this, <%= counter%>)">Start Timer</button>
                        <button class="timerButton" id="button2<%=counter%>" onclick="switchButtons(this, <%=counter%>)" style="display:none">Start Timer</button>
                    </div>
                    <div class="col-2 offset-1 text-center">
                        <button id="timerButton<%=counter%>" class="timerButton" onclick="clearClock(myTimer, <%=counter%>)">Stop Timer</button>
                    </div>
                    <div class="col-2 offset-1 text-center">
                        <button id="resetButton<%=counter%>" class="timerButton" onclick="reset(<%= counter %>)">Reset</button>
                    </div>
                </div>
            </div>
            <br />
            <%=counter += 1 %>
            <% end %>
        </div>
        <br />
        <div class="text-center">
            <%= link_to 'Back to Program', program_names_path, class: 'btn btn-success btn-large' %>
        </div>
        <br />
        <br />
    </div>
</div>
<br />
<br />
<br />
<br />
<br />