config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'static_pages#index'

namespace :instructor do 
		resources :program_names do 
			resources :weeks
		end
	end
	
	namespace :instructor do 
		resources :weeks do
			resources :titles
		end
	end
	namespace :instructor do
		resources :titles do
			resources :programs

		end	
	end
	namespace :instructor do 
		resources :weeks do
			resources :titles do 
				resources :programs 
			end
		end
	end
	
	resources :program_names, only: [:index, :show] do 
		resources :weeks, only: [:index, :show]
	end
	resources :weeks, only: [:index, :show] do 
		resources :titles, only: [:index, :show, ]
	end
	resources :titles, only: [:index, :show, :edit, :update] do
		resources :programs, only: [:index, :show]
	end
match '/weeks/complete/:id' => 'weeks#complete', as: 'complete_week', via: :put
match '/weeks/complete/:id' => 'weeks#incomplete', as: 'incomplete_week', via: :delete
match '/titles/complete/:id' => 'titles#complete', as: 'complete_title', via: :put
match '/titles/complete/:id' => 'titles#incomplete', as: 'incomplete_title', via: :delete


	resources :max_weights, only: [:index, :new, :create, :show]
	
end

app/models/program.rb
class Program < ApplicationRecord
	belongs_to :title
	default_scope { order(created_at: :asc) }
	
	
end

app/controllers/instructor/program_names_controller.rb
class Instructor::ProgramNamesController < ApplicationController
before_action :authenticate_user! 
before_action :set_program_name, only: [:edit, :update, :destroy]

def index
	@program_names = ProgramName.all

end
def new
	@program_name = ProgramName.new

end

def create
	@program_name = current_user.program_names.create(program_name_params)
redirect_to instructor_program_names_path(@program_name)
	end

	def edit
		

	end
	def update
		
		@program_name.update_attributes(program_name_params)
		redirect_to instructor_program_names_path

	end

	def destroy
		
		@program_name.destroy
		redirect_to instructor_program_names_path

	end

	private

	def set_program_name
		@program_name ||= ProgramName.find(params[:id])

	end

def program_name_params
	params.require(:program_name).permit(:program_name)
end

end

app/controllers/instructor/programs_controller.rb
class Instructor::ProgramsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_week, only: [:create, :update, :destroy]
	before_action :set_title, only: [:index, :create, :update, :destroy]
	
	def new
		@program = Program.new
	end

	def index
		@titles = Title.all 
		@programs = Program.all
	end

	def create
		
		@program = @title.programs.create(program_params)
		redirect_to instructor_week_title_path(@week,@title)
	end
	def edit
		@program = Program.find(params[:id])
	end

	def update
		@program = Program.find(params[:id])
		@program.update_attributes(program_params)
		redirect_to instructor_week_title_path(@week,@title)

	end
	def destroy

		@program = Program.find(params[:id])
		@program.destroy
		redirect_to instructor_week_title_path(@week, @title)

	end

	private
	def set_week
@week = Week.find(params[:week_id])
	end
def set_title
@title = Title.find(params[:title_id])
end 


	def program_params
		params.require(:program).permit(:exercise, :sets, :reps, :intensity, :prescribed_load, :actual_load, :tempo, :rest, :notes, :title_id)
	end
end

app/controllers/instructor/titles_controller.rb
class Instructor::TitlesController < ApplicationController
	before_action :authenticate_user!
	
	before_action :set_week, only: [:new, :show, :edit, :index, :create, :update, :destroy]
	before_action :set_title, only: [:show, :edit, :update, :destroy]

	

	def new
		@title = Title.new
	end

	def index
		@weeks = Week.all
		@titles = Title.all
		
	end

	def create
		@title = @week.titles.create(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week,@title)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show

		@titles = Title.all
		@programs = Program.all
	end

	def edit
		set_title
	end

	def update
		@title.update_attributes(title_params)
		if @title.valid?
			redirect_to instructor_week_title_path(@week, @title)
		else
			render :edit, status: :unprocessable_entity
		end

	end

	def destroy	
		@title.destroy
		redirect_to instructor_week_titles_path(@week)

	end

	private

	def set_week
		@week ||= Week.find(params[:week_id])
	end
	def set_title
		@title ||= Title.find(params[:id])
	end

	def title_params
		params.require(:title).permit(:title, :title_completed)
	end
end

app/controllers/instructor/weeks_controller.rb
class Instructor::WeeksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_program_name, only: [:new, :index, :create, :edit]
	before_action :set_week, only: [:show, :edit, :update, :destroy]
	def new	
		@week = Week.new
	end

	def create	
		@program_name.weeks.create(week_params)
		redirect_to instructor_program_name_weeks_path(@program_name)
	end

	def index
		@program_names = ProgramName.all
		@weeks = Week.all
	end

	def show
		set_week
	end

	def edit
		@program_names = ProgramName.all
		@weeks = Week.all
	end

	def update
		@week.update_attributes(week_params)
		if @week.valid?
			redirect_to instructor_program_name_weeks_path
		else
			render :edit, status: :unprocessable_entity
		end

	end
	def destroy
		@week.destroy
		redirect_to instructor_program_name_weeks_path
	end

	private

	def set_program_name
		@program_name ||= ProgramName.find(params[:program_name_id])
	end
	def set_week
		@week  ||= Week.find(params[:id])

	end
	def week_params
		params.require(:week).permit(:week_name)

	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
def index
		@titles = Title.all
		@programs = Program.all
		

	end

	def show
		@title = Title.find(params[:title_id])
		@user = User.all
		@program = Program.find(params[:id])
		@max_weight = MaxWeight.all
		@max_bench = MaxWeight.max_bench
		@max_squat = MaxWeight.max_squat
		@max_deadlift = MaxWeight.max_deadlift
		
	end

end

app/helpers/instructor/program_names_helper.rb
module Instructor::ProgramNamesHelper
end

app/helpers/instructor/programs_helper.rb
module Instructor::ProgramsHelper
end

app/helpers/instructor/titles_helper.rb
module Instructor::TitlesHelper
end

app/helpers/instructor/weeks_helper.rb
module Instructor::WeeksHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/instructor/programs/edit.html.erb
<br />
<div class="booyah-box col-10 offset-1  text-center">
    <h1> Edit Workout</h1>
    <%= simple_form_for @program, url: instructor_week_title_program_path do |f| %>
    <div class="container ">
        <div class="row">
        </div>
        <div class="row">
            <div class="col-6  exercise">
                <%= f.input :exercise, placeholder: "ex Bench Press" %>
            </div>
            <div class="col-2 ">
                <div class="sets">
                    <%= f.input :sets, placeholder: "ex 4" %>
                </div>
            </div>
            <div class=" col-2 reps">
                <div class="reps">
                    <%= f.input :reps, placeholder: "ex 6" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :intensity, placeholder: " 1RM Percentage"%>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :tempo, placeholder: "ex 1.3.1" %>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :rest, placeholser: "ex 90" %>
            </div>
        </div>
        <%= f.submit "Update", class: 'btn btn-success' %>
        <% end %>
    </div>
    <br />
</div>

app/views/instructor/programs/index.html.erb
<div class="booyah-box col-10 offset-1">
    <h1 class="text-center">Programs Index Page</h1>
    <hr />
    <% @titles.each do |title| %>
    <h1 class="text-center">
        <hr />
        <%=  title.title %>
    </h1>
    <br />
    <% @programs.each do |program| %>
    <h2 class="text-center">
        <%= program.exercise %>
    </h2>
    <br />
    <div class="text-center">
        <%= link_to 'Edit Workout', edit_instructor_title_program_path(title,program), class: 'btn btn-success btn-large' %>
    </div>
    <div class="text-center">
        <%= link_to 'Destroy', instructor_title_program_path(title, program), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    </div>
    <br />
    <div class=" text-center">
        <%= link_to 'View Workout', instructor_title_programs_path(title,program), class: 'btn btn-success btn-large' %>
    </div>
    <% end %>
    <% end %>
    <br />
    <br />
    <div class="text-center">
        <%= link_to 'Homepage', root_path, class: 'btn btn-success btn-large' %>
    </div>
</div>

app/views/instructor/programs/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
    <h1> Add a new Program</h1>
    <%= simple_form_for @program, url: instructor_week_title_programs_path do |f| %>
    <div class="form container ">
        <div class="row">
        </div>
        <div class=" row">
            <div class="col-6  exercise">
                <%= f.input :exercise, placeholder: "ex Bench" %>
            </div>
            <div class="col-3 ">
                <div class="sets">
                    <%= f.input :sets, placeholder: "ex 4" %>
                </div>
            </div>
            <div class=" col-3 reps">
                <div class="reps">
                    <%= f.input :reps, placeholder: "ex 6" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :intensity, placeholder: " 1RM Percentage"%>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :tempo, placeholder: "1.3.1" %>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                <%= f.input :rest, placeholder: "90" %>
            </div>
        </div>
        <%= f.submit "Create", class: 'btn btn-success' %>
        <% end %>
    </div>
    </br>
</div>

app/views/instructor/programs/show.html.erb
<div class="booyah-box col-10 offset-1">
    <h1> Programs show page</h1>
    <h1 class="text-center">
        <%= @program.exercise %>
    </h1>
    <hr />
    <div class="container">
        <table class="table table-striped">
            <thead>
                <div class="row">
                    <div class="col-1">
                        <tr>
                            <th>
                                <h3> Movement</h3>
                            </th>
                    </div>
                    <div class="col-1">
                        <th>
                            <h3 class="text-center">Sets</h3>
                        </th>
                    </div>
                    <div class="col-1">
                        <th>
                            <h3 class="text-center">Reps</h3>
                        </th>
                    </div>
                    <div class="col-1">
                        <th>
                            <h3 class="text-center"> Intensity</h3>
                        </th>
                    </div>
                    <div class="col-1">
                        <th>
                            <h3 class="text-center">Tempo</h3>
                        </th>
                    </div>
                    <div class="col-1">
                        <th>
                            <h3 class="text-center">Rest</h3>
                        </th>
                    </div>
                </div>
                </tr>
            </thead>
            <tbody>
                <div class="row">
                    <div class="col-1">
                        <tr>
                            <td>
                                <h3>
                                    <%= @program.exercise %>
                                </h3>
                            </td>
                    </div>
                    <div class="col-1 text-center">
                        <td>
                            <h3 class="text-center">
                                <%= @program.sets %>
                            </h3>
                        </td>
                    </div>
                    <div class="col-1">
                        <td>
                            <h3 class="text-center">
                                <%= @program.reps %>
                            </h3>
                        </td>
                    </div>
                    <div class="col-1">
                        <td>
                            <h3 class="text-center">
                                <%= @program.intensity %>
                            </h3>
                        </td>
                    </div>
                    <div class="col-1">
                        <td>
                            <h3 class="text-center">
                                <%= @program.tempo %>
                            </h3>
                        </td>
                    </div>
                    <div class="col-1">
                        <td>
                            <h3 class="text-center">
                                <%= @program.rest %>
                            </h3>
                        </td>
                    </div>
                    <div class="col-1">
                        <td>
                            <h3 class="text-center">
                                <%= link_to 'New Movement', new_instructor_title_program_path(@program), class: 'btn btn-success btn-lg' %>
                            </h3>
                        </td>
                    </div>
                </div>
                </tr>
                <br />
                <br />
    </div>
    <div class="row">
        <div class="col-12">
            <div class="text-center">
                <%= link_to 'Edit Movement', edit_instructor_program_path(@program), class: 'btn btn-success btn-lg' %>
            </div>
        </div>
    </div>
</div>